# Test Requests

### Get admin access token
# name Get Admin Access Token
POST {{host}}/oauth/token
Content-Type: application/json

{
  "grant_type": "client_credentials",
  "client_id": "{{admin_client_id}}",
  "client_secret": "{{admin_client_secret}}"
}

> {%
    client.global.set("admin_access_token", response.body.access_token);
%}

###
# @name = Rotate Keys
POST {{host}}/.internal/keys/rotate
Authorization: Bearer {{admin_access_token}}


### Create a new client app
POST http://localhost:3000/register
Content-Type: application/json

{
  "name": "My Test App",
  "permissions": [ "read:users" , "write:users" ],
  "grant_types": [ "client_credentials" ],
  "token_lifetime_seconds": 600
}

> {%
    client.global.set("clientId", response.body.client_id);
    client.global.set("clientSecret", response.body.client_secret);
%}

### Request an access token
POST http://localhost:3000/oauth/token
Content-Type: application/json

{
  "client_id": "{{clientId}}",
  "client_secret": "{{clientSecret}}",
  "grant_type": "client_credentials"
}

### Test well-known route
GET http://localhost:3000/.well-known/openid-configuration

###
GET http://localhost:3000/.well-known/jwk.json